# candidate-page-git-init:
# 	git clone -b develop git@github.com:eishin-inc/cxc-pfc-front.git
# candidate-page-git:
# 	git pull origin
# candidate-page-build:
# 	docker-compose build
# candidate-page-up:
# 	docker-compose up -d
# candidate-page-ps:
# 	docker-compose ps
# candidate-page-nginx:
# 	docker exec -it candidate-page-wrap-candidate-page-nginx-1 bash
# candidate-page-web:
# 	docker exec -it candidate-page-wrap-candidate-page-web-1 sh
# candidate-page-down:
# 	docker-compose down
git-init:
	git clone -b develop git@github.com:eishin-inc/cxc-pfc-front.git
git:
	git pull origin
build:
	docker-compose build
up:
	docker-compose up -d
up-no-d:
	docker-compose up
ps:
	docker-compose ps
nginx:
	docker exec -it candidate-page-wrap-candidate-page-nginx-1 bash
web:
	docker exec -it candidate-page-wrap-candidate-page-web-1 sh
down:
	docker-compose down
	